### ISSUE TITLE
How to limit a script to more than one mime type

### ISSUE THREAD

**Issue by ostasevych** [Raudius/files_scripts#113]
I would like to limit the script to certain number of mime types. How to make it to more than one? If I separate with comma or space the script is not willing to be saved.

**Comment by Raudius** [comment]
I dont think this is currently possible. I will look into if for a future release

**Comment by Raudius** [comment]
This was added with #130 

It will be out only for NC28+, because I didnt want to do the double work to integrate this solution for the old and new files apps.

Thanks to the new improvements Nextcloud have made to the files app, I was also able to expand the feature to allow filtering by file extensions.
