### ISSUE TITLE
Trigger on Tag Removed

### ISSUE THREAD

**Issue by ThomasCr** [Raudius/files_scripts#159]
Hi,

it would be nice to have also trigger file_scripts if a Tag is removed or changed at all....

Thanks

**Comment by ZeiTee** [comment]
This is something which has to be implemented here:
https://github.com/nextcloud/server/blob/master/apps/workflowengine/lib/Entity/File.php
So not really an issue for this repo.
I will try to do it the next days because i will find it also nice and useful, but I really don't know how difficult it is to get a PR accepted by them because its in the nextcloud server main repo.
