### ISSUE TITLE
Question: file distribution for a committee

### ISSUE THREAD

**Issue by kaffeeringe** [Raudius/files_scripts#160]
A committee has regular meetings. There are several documents that are relevant for each meeting. All members of the committee have a Nextcloud account in my cloud and I want to supply them with their documents. It can't be a group folder, as the documents are PDFs and they should be able to annotate them without others to see their notes. It should be possible to write in the PDFs as Nextcloud now makes it possible.

So I guess, every member must get their own copy of the files.

I thought file_scripts might help here. But I am not sure:

I want to use just one folder that contains a folder each for every meeting and all files concerning that meeting inside the folder. This folder and it's contents should be copied into the members own files. When I add a file it should be copied. When I delete one, if should be deleted everywhere.

I don't want to copy everthing manually. Ideally the script takes the list of users from a Nextcloud group and copies my central folder and files to each group member.

Is this possible with files_scripts?

**Comment by Raudius** [comment]
Hi Steffen,

This is certainly not a typical use case for `files_scripts` (mostly because it requires some kind of "state" between different actions; knowing which files were copied in order to later delete them) but it may be possible to make it work.

> This folder and it's contents should be copied into the members own files.

This is the easy part.  
It is already possible (although discouraged) to write a script that copies a folder to another user's files (see [`file_copy_unsafe`](https://github.com/Raudius/files_scripts/blob/master/docs/Functions.md#file_copy_unsafe)).

> When I delete one, if should be deleted everywhere.

The deleting part is the trickier one. It presents two challenges:
 1. How to identify that a file you delete is a "meeting file" which needs to be removed from other user's files.
 2. How to find the file in other user's directories.

For the first one, you could also create a separate file action to delete the file instead of using the "default" `Delete` option.

For the second one, `files_scripts` allows (again, discouraged) to delete files from other users' directories (see [`file_delete_unsafe`](https://github.com/Raudius/files_scripts/blob/master/docs/Functions.md#file_delete_unsafe)), but it requires knowing the exact path to the file. So you would also need to keep a consistent path structure for each copy and disallow the users from renaming any files/directories within.

> takes the list of users from a Nextcloud group 

This is currently not supported through the `files_scripts` API, but it would be a nice addition and something I'd be willing to implement.


Hope this helps, let me know if you have other questions.
