### ISSUE TITLE
make print(String message) visible like abort(String message)

### ISSUE THREAD

**Issue by ernolf** [Raudius/files_scripts#54]
use case:
When iterating through nodes, some nodes may be skipped due to tests. In such a case, when the script should not be aborted but only message should be thrown out (maybe with control over the collor for info, warn, error).

**Comment by Raudius** [comment]
`print` is not part of the Scripting API, so I would be hesitant overriding its behaviour. There is also a valid use-case for using `print`, which is when running file actions via `occ`.

Also due to the nature of how the scripts are executed (they are run as part of an HTTP request), its not possible to give output during runtime. 

However we could add a `message` function that queues up messages to be shown to users after the action is finished. 
Would this cover your use case?

**Comment by ernolf** [comment]
> However we could add a message function that queues up messages to be shown to users after the action is finished.

Great!

**Comment by Raudius** [comment]
Added with #66
